### ISSUE TITLE
Where to change 'environment variables'?

### ISSUE THREAD

**Issue by Meh7991** [EvanMulawski/FanControl.CorsairLink#78] opened 2023-08-18 18:24 UTC
I use the CorsairLink plugin, but I sometimes get this error:

![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/76539753/6f484e3c-1cbd-4c7e-85b2-21bbba3576d2)

Where do I set that variable? I have looked in all editable files in my FanControl directory but I cannot find anywhere to add it.

Even with the error, all my fans are still detected and respond to my fan curves, I just don't want the errors disturbing me.

**Comment by DfrostX** [comment] 2023-08-18 20:05
https://www.alphr.com/environment-variables-windows-10/

New
Name : FANCONTROL_CORSAIRLINK_DEBUG_LOGGING_ENABLED
Value: 1
Ok
Ok
Restart Fan Control

**Comment by DfrostX** [comment] 2023-08-18 20:11
I would still suggest trying to find the cause of the error log instead of just disabling it...

Maybe post your logs here for Evan to have a look at it?

**Comment by Meh7991** [comment] 2023-08-18 20:16
Ahh it's one of those environment variables, I'm dumb haha

Sure, here are my latest logs (I got the screenshotted error above about 5 mins ago). 

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12383748/CorsairLink.log)
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/12383750/log.txt)

Are those the correct logs to share? Or are there any others?

**Comment by EvanMulawski** [comment] 2023-08-18 22:42
@Meh7991 Thanks for the info and logs. This appears to be the same issue as #76.

**Comment by EvanMulawski** [comment] 2023-08-18 22:54
See #80 for progress on the root cause. Closing this as original request has been resolved.

**Closed by EvanMulawski** 2023-08-18 22:54 UTC
Labels: triage
