### ISSUE TITLE
FanControl.CoresairLink does not "play nice" with monitoring software!

### ISSUE THREAD

**Issue by chjohans** [EvanMulawski/FanControl.CorsairLink#45] opened 2023-05-07 22:38 UTC
I am aware that it's not possible to use this together with Corsair's own iCUE, Corsair simply refuses to "play ball" with others.

But, it is possible to get this to "play nice" with certain other monitoring software that is probably frequently being used by the target group for this plugin.

HWiNFO (https://www.hwinfo.com/) and SIV (http://rh-software.com/) have both implemented a named Mutex locking mechanism that makes sure that only one program will access Corsair devices at any given time. Please consider implementing this, there is some info re this on the SIV board here: https://siv.boards.net/thread/14/running-same-time-corsair-icue, and I know that Ray, the author of SIV, has more info and he's willing to share. At least I know that he has helped others to implement this. Corsair *used* to use this in their own Link software a few years ago, but dropped it and never implemented it in iCUE. But that didn't stop others from using this.

Please consider this, as it is now HWiNFO will stop reporting values for any Corsair devices that are accessed by this plugin. And, this plugin will stop getting updated data from these devices as well. It would be really useful to be able to run HWiNFO together with FanControl and this otherwise excellent plugin.

**Comment by EvanMulawski** [comment] 2023-05-07 23:07
Hi @chjohans, [this has already been implemented](https://github.com/EvanMulawski/FanControl.CorsairLink/blob/main/src/CorsairLink.Synchronization/CorsairDevicesGuard.cs) as of [v1.0.0-beta.5](https://github.com/EvanMulawski/FanControl.CorsairLink/releases/tag/v1.0.0-beta.5).

What issues are you experiencing?

**Comment by chjohans** [comment] 2023-05-08 15:49
And another thing, it takes a while for this to happen, and it seems to be rather random. I experience this maybe once every 24 hours. I went back to "Argus Monitor" after the third time, but now decided to use FanCOntrol for a while and pay attention to this.

**Comment by EvanMulawski** [comment] 2023-05-08 20:22
@chjohans For now, I'm going to assume it's an issue with HWiNFO because:

- There are no communication issues with the Commander Pro according to the log file.
- The plugin [acquires the CorsairLink mutex](https://github.com/EvanMulawski/FanControl.CorsairLink/blob/a474224c368b1d911a7795346b609b425d67856e/src/CorsairLink/HydroDevice.cs#L120-L130) for the Hydro device (and all devices for that matter) and [clears the device report buffer](https://github.com/EvanMulawski/FanControl.CorsairLink/blob/a474224c368b1d911a7795346b609b425d67856e/src/CorsairLink/HidSharpDeviceProxy.cs#L53-L59) before performing a write-read. It may be the case that HWiNFO doesn't acquire the mutex for AIO's.

1. Can you downgrade HWiNFO to version [7.40](https://www.fosshub.com/HWiNFO-old.html) and see if the issue remains? There was an [issue in version 7.42](https://www.hwinfo.com/forum/threads/7-42-update-causes-icue-fans-to-flash-off-on-every-2-4-seconds.8776/post-39222) that may be related to your current problem - it might not be completely fixed in version 7.44.

2. Ensure your BIOS is up-to-date, as there have been reports of USB communication issues with the X570 chipset.

3. You can post to the [HWiNFO Bug Reports forum](https://www.hwinfo.com/forum/forums/hwinfo32-hwinfo64-bug-reports.3/). I would be happy to work with the developers to reach a solution.

**Comment by chjohans** [comment] 2023-05-08 22:48
My BIOS is always updated :)

Just to make sure that there are no misunderstandings, you mention no comm issues with the Commander Pro, the issue I saw was with the AiO cooler only and not the commander pro. I see some CRC mismatch messages in the logfile for the AiO (H115iRGBPROXT) but of course I have no idea if those mean anything at all.

I will try HWiNFO 7.40 as you suggest. But since this error only happened randomly and 3 times so far, I will first leave the current version running until I see the same again.

Thanks for supporting this plugin the way you do, I'll buy you a coffee or two for sure!

I will indeed post in the HWiNFO forum after I see the same issue again, thanks!

**Comment by EvanMulawski** [comment] 2023-05-08 23:41
> Just to make sure that there are no misunderstandings, you mention no comm issues with the Commander Pro, the issue I saw was with the AiO cooler only and not the commander pro. I see some CRC mismatch messages in the logfile for the AiO (H115iRGBPROXT) but of course I have no idea if those mean anything at all.

The CRC mismatch errors in the log indicate an issue with the device, either with communication or the hardware itself. The last byte of the buffer is used as an error check; if the calculation used to generate that byte does not result in what was received, that's a problem.

HWiNFO reads from both the AIO and the Commander Pro. Because the logs do not indicate issues communicating with the Commander Pro, it leads me to believe the issue is with HWiNFO's communication with the AIO.

I would be curious to know if you see these CRC mismatch errors in the log when HWiNFO isn't running.

**Comment by EvanMulawski** [comment] 2023-05-21 17:41
@chjohans Any more occurrences of this issue with/without HWiNFO running?

**Comment by chjohans** [comment] 2023-05-21 18:47
I've not "lost" the temperature and fans for my AiO since the above incidents. But I still see those "SendCommand CRC mismatch" errors in the log file about 10 to 20 times each 24 hours.

I will disable HWiNFO now and see if I still log those errors and update here ina couple of days.

**Comment by chjohans** [comment] 2023-05-22 00:28
FanControl logs the same "SendCommand CRC mismatch" errors after I disabled HWiNFO, but I just had a "duh" moment. These errors seem to happen every time my computer wakes up from sleep.

I also use OpenRGB briefly to just turn off all my RGB lights, on system start-up, and then by the task scheduler every time my system wakes up from sleep. And OpenRGB has not implemented the "shared mutex" and will definitely interfere with both FanControl.CorsairLink and HWiNFO. But it has worked OK for me to just run it briefly to turn off my RGB lights as I do. It will just start, set the lights to off, and then auto quit.

I am guessing that on those occasions when I totally lost the temperature and fan readings/control for my AiO, it was a matter of maximum unlucky timing when OpenRGB would access the AiO briefly so it messed up for FanControl.CorsairLink and HWiNFO.

I will disable OpenRGB upon waking from sleep to see if I still get the same CRC errors. Will report back with the result.

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11525855/log.txt)

**Comment by chjohans** [comment] 2023-05-22 01:30
I can confirm that the "SendCommand CRC mismatch" happens even when OpenRGB is totally disabled, and every time my system wakes up from sleep.

**Comment by EvanMulawski** [comment] 2023-05-22 14:09
Closing this - created a [new issue](#47) for that error.

**Closed by EvanMulawski** 2023-05-22 14:09 UTC
Labels: synchronization-interop
