### ISSUE TITLE
Commander Core RGB flickering with SignalRGB

### ISSUE THREAD

**Issue by Asylian1** [EvanMulawski/FanControl.CorsairLink#129] opened 2023-12-14 20:01 UTC
Ever since the most recent FC update, it seems that using SignalRGB causes the LEDs to flicker sporadically. I had contacted sRGB directly about this and said it is out of their control. Can this be looked into?

Attached logs:

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13677685/log.txt)
[CorsairLink.1.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13677686/CorsairLink.1.log)

**Comment by EvanMulawski** [comment] 2023-12-15 04:40
Hi @Asylian1, can you confirm the Fan Control version you are using (e.g. v175, v174, etc.)? Does rolling back to a previous version resolve the issue?

Also, please try [v1.4.3](https://github.com/EvanMulawski/FanControl.CorsairLink/releases) of this plugin.

**Comment by Asylian1** [comment] 2023-12-15 05:20
v175 - I'll try rolling back. There were a few in the sRGB Discord saying they rolled back as well to no avail.

**Comment by Asylian1** [comment] 2023-12-15 05:48
Ran previous version (v174) there was no issues in its vanilla setup without the plugin. When I loaded in my Configurations and Plugins folder the issue returned.

v174 and v1.4.1 CorsairLink log:

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13681469/CorsairLink.log)

v174 and v1.4.3 CorsairLink log:

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13681513/log.txt)
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13681514/CorsairLink.log)

@EvanMulawski

**Comment by EvanMulawski** [comment] 2023-12-15 06:11
I think I can resolve this for the most part by porting over some improvements made during the development of iCUE Link support. Users [reported](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/111#issuecomment-1832949314) that SignalRGB stuttering significantly improved after those changes. Keep an eye out for `v1.5.0-beta.2` this weekend.

**Comment by EvanMulawski** [comment] 2023-12-15 23:47
@Asylian1 Before I create an official release, can you test the attached build with SignalRGB running? Please post the CorsairLink.log file after testing. Thanks!

[FanControl.CorsairLink-Issue129-v20231215r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13690652/FanControl.CorsairLink-Issue129-v20231215r001.zip)

**Comment by Asylian1** [comment] 2023-12-16 00:37
Unfortunately the flickering is still there upon replacing the DLL and restarting FCC (also made sure to unblock the DLL):

**Comment by Asylian1** [comment] 2023-12-16 00:37
[CorsairLink.1.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13690870/CorsairLink.1.log)

**Comment by EvanMulawski** [comment] 2023-12-16 00:42
Is the RGB turning off completely or freezing?

**Comment by Asylian1** [comment] 2023-12-16 00:53
It's a steady effect but just intermittent LED flashes every few seconds or so. @EvanMulawski

**Comment by Asylian1** [comment] 2023-12-16 00:53
The color that flashes depends on the effect, sometimes it's white flashes sometimes it's something else like a purple for example depending on the profile.

**Comment by Asylian1** [comment] 2023-12-16 00:55
It is to note I also am getting CorsairLink error popups, these started after attaching the prior logs @EvanMulawski :
[CorsairLink.1.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13690901/CorsairLink.1.log)

**Comment by EvanMulawski** [comment] 2023-12-16 02:39
Interesting - I haven't heard of flashes of colors occurring, only freezing and turning off completely.

Is SignalRGB controlling the lighting for both Commander Cores?

**Comment by Asylian1** [comment] 2023-12-16 02:59
Yea it's controlling both cores, my entire system basically no other RGB software is running.

**Comment by Asylian1** [comment] 2023-12-16 20:29
Seems even on logon I'm getting error popup windows consistently saying one or more errors have occurred @EvanMulawski :

[CorsairLink.3 - Copy.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13693867/CorsairLink.3.-.Copy.log)

**Comment by EvanMulawski** [comment] 2023-12-16 23:02
Can you confirm this issue does not occur if SignalRGB is not running? And what version of SignalRGB?

**Comment by Asylian1** [comment] 2023-12-17 00:03
Does not occur with sRGB off - version of sRGB I'm running is 2.3.43. The popups stopped actually when I closed and re-opened sRGB.

**Comment by LethalCaucasian** [comment] 2023-12-17 00:09
I’m having the same issue. Tried restarting sRGB and it didn’t fix for me.

Flashing green from light purple/pink

**Comment by LethalCaucasian** [comment] 2023-12-17 00:14
![Uploading image.jpg…]()

**Comment by EvanMulawski** [comment] 2023-12-17 00:31
@Asylian1 @LethalCaucasian Please try the attached build and post the newest CorsairLink.log file(s) after testing.

**Comment by Asylian1** [comment] 2023-12-17 00:48
Flickering still present after trying DLL:

[CorsairLink.3 - Copy (2).log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13694317/CorsairLink.3.-.Copy.2.log)

**Comment by LethalCaucasian** [comment] 2023-12-17 01:05
Flickering is still present... does seem to be less often though

**Comment by LethalCaucasian** [comment] 2023-12-17 01:29
[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13694380/CorsairLink.log)

**Comment by EvanMulawski** [comment] 2023-12-17 01:42
@Asylian1 @LethalCaucasian New build.

[FanControl.CorsairLink-Issue129-v20231216r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13694399/FanControl.CorsairLink-Issue129-v20231216r002.zip)

**Comment by LethalCaucasian** [comment] 2023-12-17 02:01
[CorsairLink.1.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13694420/CorsairLink.1.log)
Issue still persists... seems more frequent this time.

**Comment by Asylian1** [comment] 2023-12-17 02:01
Flickering still present-

[CorsairLink.4 - Copy.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13694425/CorsairLink.4.-.Copy.log)

**Comment by EvanMulawski** [comment] 2023-12-17 02:49
Does the color flickering occur when using a solid color or only effects? If only effects, does the animation speed increase the frequency? Can a short video clip of the issue be provided?

**Comment by Asylian1** [comment] 2023-12-17 02:57
I'm out currently - but it happens on both solid and animated effects. I have found that if I were to switch to solid and then select "black"  LEDs there is no flicker.

In general it seems any time an LED is on as anything other than black the flickering occurs with the color it flickers to dependent on the effect it's running.

I'll post up a clip when I get back

**Comment by LethalCaucasian** [comment] 2023-12-17 03:15
https://github.com/EvanMulawski/FanControl.CorsairLink/assets/154029520/87063ad5-fd3e-4569-9651-e9ca0ed9388c

Hard to tell from the video but appears to be a solid ring on the pump when it flickers.

**Comment by EvanMulawski** [comment] 2023-12-17 03:33
Would you be able to provide a USB packet capture while both Fan Control and SignalRGB are running?

Packet capture instructions:

1. Install the latest version of Wireshark and install USBPcap when prompted during the installation process. 
2. Launch Wireshark as administrator and start a USBPcap capture (double-click USBPcap1 under Capture on the welcome screen).
3. Wait until this issue occurs, then stop the capture about a minute later.
4. Save the capture (should be a pcapng file), ZIP it, and upload it here.

Let me know if you need any additional help or information.

**Comment by LethalCaucasian** [comment] 2023-12-17 03:37
I will work on this tomorrow if it hasn’t already been provided.

**Comment by Asylian1** [comment] 2023-12-17 06:06
This is what I'm seeing on my end. It appears upon second observation the flickering is only occurring with devices connected into my H150 Elite Commander Core and not my off the shelf Commander Core: @EvanMulawski 

https://github.com/EvanMulawski/FanControl.CorsairLink/assets/77643816/c915daa3-591c-4211-bf50-be735e1a107a

**Comment by LethalCaucasian** [comment] 2023-12-17 13:13
[USB capture.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13696193/USB.capture.zip)

**Comment by EvanMulawski** [comment] 2023-12-17 20:55
@Asylian1 @LethalCaucasian New build.

[FanControl.CorsairLink-Issue129-v20231217r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13697731/FanControl.CorsairLink-Issue129-v20231217r001.zip)

**Comment by ThatZeek** [comment] 2023-12-17 21:36
Jus

> @Asylian1 @LethalCaucasian New build.
> 
> [FanControl.CorsairLink-Issue129-v20231217r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13697731/FanControl.CorsairLink-Issue129-v20231217r001.zip)

Just tried this, still getting flickering - Im on V175 of FC and  V2.3.43 of sRGB

**Comment by EvanMulawski** [comment] 2023-12-17 22:09
@Heal-Bot Any idea why this flash of color is occurring on only the Commander Core `0c32` variant?

**Comment by Asylian1** [comment] 2023-12-18 03:29
Flickering still happening, again with the H150i Elite LCD Commander Core flickering @EvanMulawski :

[CorsairLink.6 - Copy.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13699181/CorsairLink.6.-.Copy.log)

**Comment by EvanMulawski** [comment] 2023-12-18 05:00
@Asylian1 @LethalCaucasian @ThatZeek Does this issue occur using [this build of OpenRGB](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/101#issuecomment-1806536056)? (Ensure SignalRGB is not running when testing OpenRGB.)

**Comment by Asylian1** [comment] 2023-12-18 05:17
@EvanMulawski No flickering when using OpenRGB on any arbitrary lighting scheme that I could see:

[CorsairLink.7 - Copy.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/13699653/CorsairLink.7.-.Copy.log)

**Comment by ThatZeek** [comment] 2023-12-18 05:19
> @Asylian1 @LethalCaucasian @ThatZeek Does this issue occur using [this build of OpenRGB](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/101#issuecomment-1806536056)? (Ensure SignalRGB is not running when testing OpenRGB.)

Can try when I'm home later tonight. I haven't been using openRGB as they don't support my ram (corsair platinum)

**Comment by LethalCaucasian** [comment] 2023-12-19 00:38
Thank you for taking a look into the issue!

**Comment by Lacysda** [comment] 2023-12-22 08:57
Have you heard back from signal rgb on them fixing it? Wondering if it'll just be easier to switch to open rgb

**Comment by ThatZeek** [comment] 2023-12-22 09:02
> Have you heard back from signal rgb on them fixing it? Wondering if it'll just be easier to switch to open rgb

They fixed it in a recent beta. No issues so far. 
Open RGB does not support the commander core xt yet :(

**Comment by EvanMulawski** [comment] 2023-12-22 16:03
@ThatZeek Do you know which beta version? Looks like it's either `2.3.45` or `2.3.46`, but I'm not seeing a specific reference to this issue in their change logs.

**Comment by Lacysda** [comment] 2023-12-22 16:05
I'm not too sure which fixed it but currently I updated to 2.3.46 and the issue is gone

**Comment by EvanMulawski** [comment] 2023-12-22 16:17
OK - closing this as resolved by SignalRGB team in version `2.3.46`. Thanks, everyone!

**Closed by EvanMulawski** 2023-12-22 16:17 UTC
Labels: synchronization-interop, troubleshooting, external
