### ISSUE TITLE
FanControl.CorsairLink Commander Pro Temperature Sensor

### ISSUE THREAD

**Issue by GiantSparta** [EvanMulawski/FanControl.CorsairLink#46] opened 2023-05-12 09:07 UTC
I'm having issues with the Temperature sensor readouts, I know that you needed to manually set the fans and that worked great but when adding a temperature sensor to the Commander Pro it displays the temp and it turns on and off every 1 second.

**Comment by EvanMulawski** [comment] 2023-05-12 18:16
Hi @GiantSparta:

1. Please reply with the `log.txt` file (located in the Fan Control root directory) attached.
2. Please provide a screenshot/video of the issue.
3. Please provide the version numbers of Fan Control and the CorsairLink plugin you are using.

Note: I use a Commander Pro and am not experiencing this issue.

**Comment by GiantSparta** [comment] 2023-05-12 20:47
> Hi @GiantSparta:
> 
> 1. Please reply with the `log.txt` file (located in the Fan Control root directory) attached.
> 2. Please provide a screenshot/video of the issue.
> 3. Please provide the version numbers of Fan Control and the CorsairLink plugin you are using.
> 
> Note: I use a Commander Pro and am not experiencing this issue.

1. log file attached:
[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11467613/log.txt)

2. gif attached: 
![Animation](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/45576830/d77459df-3f7d-41b8-987e-cc5e3f85cbfa)

3. i'm using Fan control V156 and fancontrol.corsairlink v1.1.2

See the gif attached it's displaying the temp and then displaying nothing it's looping somehow

**Comment by EvanMulawski** [comment] 2023-05-12 21:20
Thanks @GiantSparta. Can you install/run [HWiNFO64](https://www.hwinfo.com/download/) in Sensors Only mode with CorsairLink support enabled (Settings > Safety > check **CorsairLink and Asetek Support**) and see if the readings match? The device will be named "Corsair CLCP" in the list as shown below.

![image](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/1044791/a49de454-cbab-4ba3-9395-3f81cde0a1e5)

**Comment by GiantSparta** [comment] 2023-05-13 08:29
I think my Commander Pro is broken, the voltages fluctuate all over the place same with the RPM and Temp. Maybe overloaded it one time.
![Animation2](https://github.com/EvanMulawski/FanControl.CorsairLink/assets/45576830/648c6051-2cfc-4d97-adc2-2e69fe967874)

**Comment by EvanMulawski** [comment] 2023-05-13 17:27
@GiantSparta I'm going to close this as the problem is unrelated to the CorsairLink plugin, but you can try the following:

1. Ensure your BIOS is up-to-date to ensure any USB connectivity problems are resolved.
2. Ensure no other programs are running that attempt to communicate with the Commander Pro.
3. Try connecting the Commander Pro to a different USB header on your motherboard.

If none of those suggestions resolve the issue, you are likely correct in your assumption that there is an issue with the device itself.

**Closed by EvanMulawski** 2023-05-13 17:27 UTC
Labels: triage
