### ISSUE TITLE
Device control issue when switching configurations

### ISSUE THREAD

**Issue by DfrostX** [EvanMulawski/FanControl.CorsairLink#58] opened 2023-06-24 22:17 UTC
Hi Evan

I think I found a bug/ unwanted behavior with the corsair PSU control you added in the latest BETA.

When switching between 2 FanControl profiles that have a different % for the PSU fan, the PSU looses its ability to control it properly.

As an example, if profile 1 is set to 30% (560rpm) and profile 2 is set to 40% (740rpm), the initial load of profile 1 goes as expected (0rpm to 560rpm). If I switch to profile 2 (expected 740rpm), the fan ramp up to 880rpm (equivalent to 50%) despite showing 40% in FanControl.

Changing back to profile 1, the fan still stay at 880rpm (50%). At this point, it seems like the scaling of % vs rpm is completely off (ex 100% is now 1300rpm instead of 1500rpm, the unit will refuse to go below 880rpm). Also, turning the fan off will work, but will not fix the issue... The unit will go back to the same behavior if set from 1-100%. Only closing FanControl and starting it again will make the control go back to normal.

From my testing, I think you initialize the software control of the unit at 50% right? I noticed because when starting FanControl with a 30% value (550rpm), the fan goes from 0 to 880rpm then goes back to the set 30% (560rpm). Would it be possible to initialize at duty cycle value (30%)?

**Comment by EvanMulawski** [comment] 2023-06-25 02:44
That is very interesting. Can you reproduce this with debug logging enabled and post the log file? To enable debug logging, set the `FANCONTROL_CORSAIRLINK_DEBUG_LOGGING_ENABLED` environment variable to `1` and restart Fan Control.

**Comment by DfrostX** [comment] 2023-06-25 13:10
See below

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11859779/log.txt)

**Comment by EvanMulawski** [comment] 2023-06-25 19:12
@DfrostX Please try the attached build with debug logging enabled and provide the log file after testing.

[FanControl.CorsairLink-Issue58-v20230625r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11860582/FanControl.CorsairLink-Issue58-v20230625r002.zip)

**Comment by DfrostX** [comment] 2023-06-26 01:18
@EvanMulawski ok so I tried the plugin above.

It has improved, but I can still see the error happening, but after a the 2nd cycle of changing profile. Which I think was happening on the first profile change.

Now about the debug log, as soon as I enable the environnement variable in Windows (1) and start FanControl, I get an error message and cannot do anything (except close the program).

See attached

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11861553/log.txt)

**Comment by EvanMulawski** [comment] 2023-06-26 02:04
Thanks. Looks like the logging issue is due to Fan Control's file logger not using a lock to synchronize access to the log file. I'll have to implement a separate logger and use a separate log file.

I'm continuing to investigate the original issue.

**Comment by EvanMulawski** [comment] 2023-06-26 04:07
@DfrostX Please reproduce the issue using the attached build with debug logging enabled and provide the new `CorsairLink.log` log file after testing.

[FanControl.CorsairLink-Issue58-v20230626r001.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11862973/FanControl.CorsairLink-Issue58-v20230626r001.zip)

**Comment by DfrostX** [comment] 2023-06-26 11:01
@EvanMulawski 

Ok so this build still gives me an error with loogin enabled (1) but I found out that if I do not open the FanControl gui, I could still change profile using the tray icon while the corsairlink.txt file would still update, so I carried on tha way.

It took many profile chnge for the issue to happen. After maybe 6 changes, a log.txt appeared, so I'm also adding it here for you to look at. I did not count, but the issue happened after maybe 12 profile changes.

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11867767/CorsairLink.log)

[log.txt](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11867769/log.txt)

**Comment by EvanMulawski** [comment] 2023-06-26 13:58
@DfrostX New build to fix logging issue.

[FanControl.CorsairLink-Issue58-v20230626r002.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11870098/FanControl.CorsairLink-Issue58-v20230626r002.zip)

**Comment by DfrostX** [comment] 2023-06-26 15:27
@EvanMulawski This build fixed the logger issue.

I was able to reproduce the issue much faster using a graph instead. Both profile used the same graph...

On first change from profile 1 to 2, the fan that should have stayed at 560rpm (30%) given the temp in the graph, ramped to 880rpm. Setting the speed manually to 100%, the  max speed it went is 1300rpm (expected 1500rpm). setting it to 30%, it did not go below 880rpm (50%).

See below log

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11870985/CorsairLink.log)

**Comment by EvanMulawski** [comment] 2023-06-26 17:22
@DfrostX New build.

[FanControl.CorsairLink-Issue58-v20230626r003.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11871957/FanControl.CorsairLink-Issue58-v20230626r003.zip)

**Comment by DfrostX** [comment] 2023-06-26 17:37
@EvanMulawski 

Switching from a profile at 30% to a 35% one created the issue right away.

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11872103/CorsairLink.log)

**Comment by EvanMulawski** [comment] 2023-06-26 17:59
Identified the issue - working on a fix.

**Comment by EvanMulawski** [comment] 2023-06-26 21:08
@DfrostX New build.

[FanControl.CorsairLink-Issue58-v20230626r004.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11874079/FanControl.CorsairLink-Issue58-v20230626r004.zip)

**Comment by DfrostX** [comment] 2023-06-26 21:52
@EvanMulawski well I tried reproducing the issue thru various combination, even some weird ones like going from a profile at 10% to a 0%, or a 35% to 20% and was not able to reproduce it.

I also made sure that the 0% mode was still functionnal, and that FanControl opened and closed properly, multiple times.

I will keep testing, but at first glance the new build look like it fixed the issue.

Here is the log in case you want to have a look

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11874943/CorsairLink.log)

**Comment by EvanMulawski** [comment] 2023-06-26 23:37
@DfrostX New build - previous build was writing to the device unnecessarily.

[FanControl.CorsairLink-Issue58-v20230626r005.zip](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11875505/FanControl.CorsairLink-Issue58-v20230626r005.zip)

**Comment by DfrostX** [comment] 2023-06-27 01:13
@EvanMulawski 

Gotcha. New build, from a user perspective, react exactly the same as the previous one.

I noticed that when switching from a profile at 30% to another one also at 30%, the fan will ramp up a bit before going back to the set %. Not sure why but it work flawlessly anyway, so not an issue.

See the log

[CorsairLink.log](https://github.com/EvanMulawski/FanControl.CorsairLink/files/11876619/CorsairLink.log)

**Comment by EvanMulawski** [comment] 2023-06-27 02:57
Fixed in v1.3.0-beta.2

**Closed by EvanMulawski** 2023-06-27 02:57 UTC
Labels: bug

**Comment by EvanMulawski** [comment] 2023-06-27 03:51
> I noticed that when switching from a profile at 30% to another one also at 30%, the fan will ramp up a bit before going back to the set %. Not sure if this is intended, but it work flawlessly anyway, so not an issue.

This is because Fan Control "resets" every fan controller when switching configurations and a reset should restore the fan to an acceptable default. Every device currently has a default of 50% but I may change that based on feedback.
